# Generated by Django 5.2 on 2025-04-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0002_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='room_type',
            field=models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '3 Bedroom'), ('3 Bedroom', '3 Bedroom')], default='Bedsitter', max_length=50),
        ),
    ]
