# Generated by Django 5.2 on 2025-04-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0003_property_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='room_type',
            field=models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('3 Bedroom', '3 Bedroom')], default='Bedsitter', max_length=50),
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('bank', 'bank'), ('mpesa', 'mpesa'), ('cheque', 'cheque'), ('other', 'other')], default='mpesa', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental_management.tenant')),
            ],
        ),
    ]
